### PR TITLE
keys/employees-keys: Add key

### PR DESCRIPTION
**Pull request by mkopec**
Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>

### CODE REVIEW

**Comment by macpijan** [comment]
@mkopec I think this one is not signed by me or anyone else

**Comment by mkopec** [comment]
I updated the PR with a signed key

**Comment by macpijan** [comment]
@mkopec needs a rebase

**Comment by mkopec** [comment]
@macpijan Rebased

**Pull request merged**
