### PR TITLE
dasharo: dts: extend 1.2.x release key

### PR DESCRIPTION
**Pull request by macpijan**
Extended subkey as well, please verify

### CODE REVIEW

**Comment by tym2k1** [comment]
```sh
$ gpg --show-keys --with-colons dasharo-tools-suite-open-source-software-release-1.2.x-signing-key-pub.asc
pub:-:4096:1:97CAD56CFC68629B:1710772496:::-:::cSC::::::23::0:
fpr:::::::::AD67DF3B8787B81AD8D4918697CAD56CFC68629B:
uid:-::::1710772496::AF2E741F1BE3DC48056F89DFA5E242C0B1B023E5::Dasharo release 0.9.x for PC Engines signing key <contact@dasharo.com>::::::::::0:
sub:-:4096:1:124D1B738C927085:1710772496:1742308499:::::s::::::23:
fpr:::::::::6B767C61EF8291899B88E88A124D1B738C927085:
```

The subkey expires at `Tue Mar 18 03:34:59 PM CET 2025` while the pubkey doesn't have expiration date at all. 

The UID also seems wrong. Previously the UID was `Dasharo Tools Suite open-source software release 1.2.x signing key`   not `Dasharo release 0.9.x for PC Engines signing key <contact@dasharo.com>`

**Review by tym2k1 — CHANGES_REQUESTED** [review]
```sh
$ gpg --show-keys --with-colons dasharo-tools-suite-open-source-software-release-1.2.x-signing-key-pub.asc
pub:-:4096:1:97CAD56CFC68629B:1710772496:::-:::cSC::::::23::0:
fpr:::::::::AD67DF3B8787B81AD8D4918697CAD56CFC68629B:
uid:-::::1710772496::AF2E741F1BE3DC48056F89DFA5E242C0B1B023E5::Dasharo release 0.9.x for PC Engines signing key <contact@dasharo.com>::::::::::0:
sub:-:4096:1:124D1B738C927085:1710772496:1742308499:::::s::::::23:
fpr:::::::::6B767C61EF8291899B88E88A124D1B738C927085:
```

The subkey expires at `Tue Mar 18 03:34:59 PM CET 2025` while the pubkey doesn't have expiration date at all. 

The UID also seems wrong. Previously the UID was `Dasharo Tools Suite open-source software release 1.2.x signing key`   not `Dasharo release 0.9.x for PC Engines signing key <contact@dasharo.com>`

**Comment by macpijan** [comment]
@tym2k1 Exported different key :disappointed: Should be fixed.

**Review by tym2k1 — APPROVED** [review]
pubkey expiration date: `Wed Jun 25 01:57:02 PM CEST 2025`
subkey expiration date: `Wed Jun 25 01:57:23 PM CEST 2025`
UID: `Dasharo Tools Suite open-source software release 1.2.x signing ke`

LGTM

**Pull request merged**
