### PR TITLE
keys/owner-key: new key and revoked version of previous one

### PR DESCRIPTION
**Pull request by pietrushnic**
Key is replaced due to missing USB toke which consist of 0xE0309B2D85A67E846329E34BB2EE71E967AA9E4C key. All signatures made by 0xE0309B2D85A67E846329E34BB2EE71E967AA9E4C or any of its subkey should be considered invalid since 7th October 2023.

### CODE REVIEW

**Comment by pietrushnic** [comment]
@macpijan pre-commit fails due to missing config file.

**Comment by macpijan** [comment]
@pietrushnic Then let's merge https://github.com/3mdeb/3mdeb-secpack/pull/102 first :)

**Comment by pietrushnic** [comment]
@macpijan I would be glad to merge #102, but there are still not resolved conversations there.

**Comment by pietrushnic** [comment]
@macpijan #102 was merged, but according to your comments in other PRs, those are just public keys, so pre-commit will not help here much. Can you take a look and approve or let me know what I should do that make it ready for approval?

**Review by macpijan — APPROVED** [review]

**Pull request merged**
